// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (i *Item) Children(ctx context.Context) (result []*Item, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = i.NamedChildren(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = i.Edges.ChildrenOrErr()
	}
	if IsNotLoaded(err) {
		result, err = i.QueryChildren().All(ctx)
	}
	return result, err
}

func (i *Item) Parents(ctx context.Context) (result []*Item, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = i.NamedParents(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = i.Edges.ParentsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = i.QueryParents().All(ctx)
	}
	return result, err
}
