// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/breadchris/hn/ent/predicate"
	"github.com/breadchris/hn/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (uu *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetCreated sets the "created" field.
func (uu *UserUpdate) SetCreated(i int64) *UserUpdate {
	uu.mutation.ResetCreated()
	uu.mutation.SetCreated(i)
	return uu
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (uu *UserUpdate) SetNillableCreated(i *int64) *UserUpdate {
	if i != nil {
		uu.SetCreated(*i)
	}
	return uu
}

// AddCreated adds i to the "created" field.
func (uu *UserUpdate) AddCreated(i int64) *UserUpdate {
	uu.mutation.AddCreated(i)
	return uu
}

// ClearCreated clears the value of the "created" field.
func (uu *UserUpdate) ClearCreated() *UserUpdate {
	uu.mutation.ClearCreated()
	return uu
}

// SetKarma sets the "karma" field.
func (uu *UserUpdate) SetKarma(i int) *UserUpdate {
	uu.mutation.ResetKarma()
	uu.mutation.SetKarma(i)
	return uu
}

// SetNillableKarma sets the "karma" field if the given value is not nil.
func (uu *UserUpdate) SetNillableKarma(i *int) *UserUpdate {
	if i != nil {
		uu.SetKarma(*i)
	}
	return uu
}

// AddKarma adds i to the "karma" field.
func (uu *UserUpdate) AddKarma(i int) *UserUpdate {
	uu.mutation.AddKarma(i)
	return uu
}

// SetAbout sets the "about" field.
func (uu *UserUpdate) SetAbout(s string) *UserUpdate {
	uu.mutation.SetAbout(s)
	return uu
}

// SetNillableAbout sets the "about" field if the given value is not nil.
func (uu *UserUpdate) SetNillableAbout(s *string) *UserUpdate {
	if s != nil {
		uu.SetAbout(*s)
	}
	return uu
}

// ClearAbout clears the value of the "about" field.
func (uu *UserUpdate) ClearAbout() *UserUpdate {
	uu.mutation.ClearAbout()
	return uu
}

// Mutation returns the UserMutation object of the builder.
func (uu *UserUpdate) Mutation() *UserMutation {
	return uu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, uu.sqlSave, uu.mutation, uu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UserUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UserUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uu *UserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeString))
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.Created(); ok {
		_spec.SetField(user.FieldCreated, field.TypeInt64, value)
	}
	if value, ok := uu.mutation.AddedCreated(); ok {
		_spec.AddField(user.FieldCreated, field.TypeInt64, value)
	}
	if uu.mutation.CreatedCleared() {
		_spec.ClearField(user.FieldCreated, field.TypeInt64)
	}
	if value, ok := uu.mutation.Karma(); ok {
		_spec.SetField(user.FieldKarma, field.TypeInt, value)
	}
	if value, ok := uu.mutation.AddedKarma(); ok {
		_spec.AddField(user.FieldKarma, field.TypeInt, value)
	}
	if value, ok := uu.mutation.About(); ok {
		_spec.SetField(user.FieldAbout, field.TypeString, value)
	}
	if uu.mutation.AboutCleared() {
		_spec.ClearField(user.FieldAbout, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uu.mutation.done = true
	return n, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetCreated sets the "created" field.
func (uuo *UserUpdateOne) SetCreated(i int64) *UserUpdateOne {
	uuo.mutation.ResetCreated()
	uuo.mutation.SetCreated(i)
	return uuo
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableCreated(i *int64) *UserUpdateOne {
	if i != nil {
		uuo.SetCreated(*i)
	}
	return uuo
}

// AddCreated adds i to the "created" field.
func (uuo *UserUpdateOne) AddCreated(i int64) *UserUpdateOne {
	uuo.mutation.AddCreated(i)
	return uuo
}

// ClearCreated clears the value of the "created" field.
func (uuo *UserUpdateOne) ClearCreated() *UserUpdateOne {
	uuo.mutation.ClearCreated()
	return uuo
}

// SetKarma sets the "karma" field.
func (uuo *UserUpdateOne) SetKarma(i int) *UserUpdateOne {
	uuo.mutation.ResetKarma()
	uuo.mutation.SetKarma(i)
	return uuo
}

// SetNillableKarma sets the "karma" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableKarma(i *int) *UserUpdateOne {
	if i != nil {
		uuo.SetKarma(*i)
	}
	return uuo
}

// AddKarma adds i to the "karma" field.
func (uuo *UserUpdateOne) AddKarma(i int) *UserUpdateOne {
	uuo.mutation.AddKarma(i)
	return uuo
}

// SetAbout sets the "about" field.
func (uuo *UserUpdateOne) SetAbout(s string) *UserUpdateOne {
	uuo.mutation.SetAbout(s)
	return uuo
}

// SetNillableAbout sets the "about" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableAbout(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetAbout(*s)
	}
	return uuo
}

// ClearAbout clears the value of the "about" field.
func (uuo *UserUpdateOne) ClearAbout() *UserUpdateOne {
	uuo.mutation.ClearAbout()
	return uuo
}

// Mutation returns the UserMutation object of the builder.
func (uuo *UserUpdateOne) Mutation() *UserMutation {
	return uuo.mutation
}

// Where appends a list predicates to the UserUpdate builder.
func (uuo *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	uuo.mutation.Where(ps...)
	return uuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated User entity.
func (uuo *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, uuo.sqlSave, uuo.mutation, uuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UserUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uuo *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeString))
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uuo.mutation.Created(); ok {
		_spec.SetField(user.FieldCreated, field.TypeInt64, value)
	}
	if value, ok := uuo.mutation.AddedCreated(); ok {
		_spec.AddField(user.FieldCreated, field.TypeInt64, value)
	}
	if uuo.mutation.CreatedCleared() {
		_spec.ClearField(user.FieldCreated, field.TypeInt64)
	}
	if value, ok := uuo.mutation.Karma(); ok {
		_spec.SetField(user.FieldKarma, field.TypeInt, value)
	}
	if value, ok := uuo.mutation.AddedKarma(); ok {
		_spec.AddField(user.FieldKarma, field.TypeInt, value)
	}
	if value, ok := uuo.mutation.About(); ok {
		_spec.SetField(user.FieldAbout, field.TypeString, value)
	}
	if uuo.mutation.AboutCleared() {
		_spec.ClearField(user.FieldAbout, field.TypeString)
	}
	_node = &User{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uuo.mutation.done = true
	return _node, nil
}
